import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { gql } from "@apollo/client";
import client from "../pages/api/apollo-client";

export default function Home() {
  const fetchData = async () => {
    const { data } = await client.query({
      query: gql`
        query products {
          products {
            description
            price
          }
        }
      `,
    });
    return await data;
  };
  const data = fetchData();
  console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-4xl text-red-500">Test</h1>
      </main>
    </div>
  );
}
