# Generated by Django 3.2.6 on 2021-08-15 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomestatement',
            name='acceptedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=255),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, max_length=255),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='fillingDate',
            field=models.DateField(default=django.utils.timezone.now, max_length=255),
        ),
    ]
