# Generated by Django 3.2.6 on 2021-08-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomestatement',
            name='key',
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='link',
            field=models.URLField(default='None', primary_key=True, serialize=False),
        ),
    ]
