# Generated by Django 3.2.6 on 2021-08-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210816_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomestatement',
            name='finalLink',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='link',
            field=models.URLField(),
        ),
    ]
