# Generated by Django 3.2.6 on 2021-08-16 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210816_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetStatement',
            fields=[
                ('date', models.DateField(default=django.utils.timezone.now, max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('fillingDate', models.DateField(default=django.utils.timezone.now, max_length=255)),
                ('acceptedDate', models.DateField(default=django.utils.timezone.now, max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('cashAndCashEquivalents', models.BigIntegerField(default=0)),
                ('shortTermInvestments', models.BigIntegerField(default=0)),
                ('cashAndShortTermInvestments', models.BigIntegerField(default=0)),
                ('netReceivables', models.BigIntegerField(default=0)),
                ('inventory', models.BigIntegerField(default=0)),
                ('otherCurrentAssets', models.BigIntegerField(default=0)),
                ('totalCurrentAssets', models.BigIntegerField(default=0)),
                ('propertyPlantEquipmentNet', models.BigIntegerField(default=0)),
                ('goodwill', models.BigIntegerField(default=0)),
                ('intangibleAssets', models.BigIntegerField(default=0)),
                ('goodwillAndIntangibleAssets', models.BigIntegerField(default=0)),
                ('longTermInvestments', models.BigIntegerField(default=0)),
                ('taxAssets', models.BigIntegerField(default=0)),
                ('otherNonCurrentAssets', models.BigIntegerField(default=0)),
                ('totalNonCurrentAssets', models.BigIntegerField(default=0)),
                ('otherAssets', models.BigIntegerField(default=0)),
                ('totalAssets', models.BigIntegerField(default=0)),
                ('accountPayables', models.BigIntegerField(default=0)),
                ('shortTermDebt', models.BigIntegerField(default=0)),
                ('taxPayables', models.BigIntegerField(default=0)),
                ('deferredRevenue', models.BigIntegerField(default=0)),
                ('otherCurrentLiabilities', models.BigIntegerField(default=0)),
                ('totalCurrentLiabilities', models.BigIntegerField(default=0)),
                ('longTermDebt', models.BigIntegerField(default=0)),
                ('deferredRevenueNonCurrent', models.BigIntegerField(default=0)),
                ('deferredTaxLiabilitiesNonCurrent', models.BigIntegerField(default=0)),
                ('otherNonCurrentLiabilities', models.BigIntegerField(default=0)),
                ('totalNonCurrentLiabilities', models.BigIntegerField(default=0)),
                ('otherLiabilities', models.BigIntegerField(default=0)),
                ('totalLiabilities', models.BigIntegerField(default=0)),
                ('commonStock', models.BigIntegerField(default=0)),
                ('retainedEarnings', models.BigIntegerField(default=0)),
                ('accumulatedOtherComprehensiveIncomeLoss', models.BigIntegerField(default=0)),
                ('othertotalStockholdersEquity', models.BigIntegerField(default=0)),
                ('totalStockholdersEquity', models.BigIntegerField(default=0)),
                ('totalLiabilitiesAndStockholdersEquity', models.BigIntegerField(default=0)),
                ('totalInvestments', models.BigIntegerField(default=0)),
                ('netDebt', models.BigIntegerField(default=0)),
                ('link', models.URLField(default='None', primary_key=True, serialize=False)),
                ('finalLink', models.URLField()),
            ],
            options={
                'verbose_name': 'Balance Sheet Statement',
                'db_table': 'app_balancesheetstatement',
            },
        ),
    ]
