# Generated by Django 3.2.6 on 2021-08-16 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_balancesheetstatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowStatement',
            fields=[
                ('date', models.DateField(default=django.utils.timezone.now, max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('fillingDate', models.DateField(default=django.utils.timezone.now, max_length=255)),
                ('acceptedDate', models.DateField(default=django.utils.timezone.now, max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('netIncome', models.BigIntegerField(default=0)),
                ('depreciationAndAmortization', models.BigIntegerField(default=0)),
                ('deferredIncomeTax', models.BigIntegerField(default=0)),
                ('stockBasedCompensation', models.BigIntegerField(default=0)),
                ('changeInWorkingCapital', models.BigIntegerField(default=0)),
                ('accountsReceivables', models.BigIntegerField(default=0)),
                ('inventory', models.BigIntegerField(default=0)),
                ('accountsPayables', models.BigIntegerField(default=0)),
                ('otherWorkingCapital', models.BigIntegerField(default=0)),
                ('otherNonCashItems', models.BigIntegerField(default=0)),
                ('netCashProvidedByOperatingActivities', models.BigIntegerField(default=0)),
                ('investmentsInPropertyPlantAndEquipment', models.BigIntegerField(default=0)),
                ('acquisitionsNet', models.BigIntegerField(default=0)),
                ('purchasesOfInvestments', models.BigIntegerField(default=0)),
                ('salesMaturitiesOfInvestments', models.BigIntegerField(default=0)),
                ('otherInvestingActivites', models.BigIntegerField(default=0)),
                ('netCashUsedForInvestingActivites', models.BigIntegerField(default=0)),
                ('debtRepayment', models.BigIntegerField(default=0)),
                ('commonStockIssued', models.BigIntegerField(default=0)),
                ('commonStockRepurchased', models.BigIntegerField(default=0)),
                ('dividendsPaid', models.BigIntegerField(default=0)),
                ('otherFinancingActivites', models.BigIntegerField(default=0)),
                ('netCashUsedProvidedByFinancingActivities', models.BigIntegerField(default=0)),
                ('effectOfForexChangesOnCash', models.BigIntegerField(default=0)),
                ('netChangeInCash', models.BigIntegerField(default=0)),
                ('cashAtEndOfPeriod', models.BigIntegerField(default=0)),
                ('cashAtBeginningOfPeriod', models.BigIntegerField(default=0)),
                ('operatingCashFlow', models.BigIntegerField(default=0)),
                ('capitalExpenditure', models.BigIntegerField(default=0)),
                ('freeCashFlow', models.BigIntegerField(default=0)),
                ('link', models.URLField(default='None', primary_key=True, serialize=False)),
                ('finalLink', models.URLField()),
            ],
            options={
                'verbose_name': 'Cash Flow Statement',
                'db_table': 'app_cashflowstatement',
            },
        ),
    ]
