# Generated by Django 3.2.6 on 2021-08-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_cashflowstatement"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesheetstatement",
            name="index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cashflowstatement",
            name="index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="index",
            field=models.IntegerField(default=0),
        ),
    ]
