# Generated by Django 3.2.6 on 2021-09-01 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_piotroskiscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('symbol', models.CharField(default='key', max_length=255, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0)),
                ('beta', models.FloatField(default=0)),
                ('volAvg', models.BigIntegerField(default=0)),
                ('mktCap', models.BigIntegerField(default=0)),
                ('lastDiv', models.FloatField(default=0)),
                ('range', models.CharField(max_length=255)),
                ('changes', models.FloatField(default=0)),
                ('companyName', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('isin', models.CharField(max_length=255)),
                ('cusip', models.CharField(max_length=255)),
                ('exchange', models.CharField(max_length=255)),
                ('exchangeShortName', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('website', models.URLField(default='None')),
                ('description', models.CharField(max_length=255)),
                ('ceo', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('fullTimeEmployees', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.BigIntegerField(default=0)),
                ('dcfDiff', models.FloatField(default=0)),
                ('dcf', models.FloatField(default=0)),
                ('image', models.URLField(default='None')),
                ('ipoDate', models.DateField(default=django.utils.timezone.now, max_length=255)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'db_table': 'app_companyprofile',
            },
        ),
    ]
