# Generated by Django 3.2.6 on 2021-09-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_magicformulascore'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicformulascore',
            name='companyName',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='magicformulascore',
            name='industry',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='magicformulascore',
            name='sector',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='magicformulascore',
            name='website',
            field=models.URLField(default='None'),
        ),
        migrations.AddField(
            model_name='piotroskiscore',
            name='companyName',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='piotroskiscore',
            name='industry',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='piotroskiscore',
            name='sector',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='piotroskiscore',
            name='website',
            field=models.URLField(default='None'),
        ),
    ]
